name: Publish to FoundryVTT
on: 
  workflow_dispatch:
    inputs: 
      tag: 
        description: "The release tag to create"
        default: "latest"
        required: true
        type: string
jobs: 
  publish:
    permissions: write-all
    name: Publish to FoundryVTT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm ci
      - name: Package SRD Content
        run: |
          npm run pack --if-present
      - name: Compress
        run: |
          cd ../
          rm -rf utopia-foundryvtt.zip
          rm -rf utopia.zip
          zip -r utopia.zip utopia-foundryvtt -x ".git/*" ".github/*"
      - name: Add Build to Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.tag }}
          tag_name: ${{ inputs.tag}}
          files: |
            ../utopia.zip
            ../utopia-foundryvtt/system.json
          generate_release_notes: true
          draft: false
      - name: Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.foundryvtt.com/_api/packages/release_version/"
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "Authorization": "${{ secrets.FoundryVTT_API_Key }}"}'
          data: '{ "id": "utopia", "dry-run": false, "release": { "version": "${{ inputs.tag }}", "manifest": "https://github.com/VoltaicGRiD/utopia-foundryvtt/releases/download/${{ inputs.tag }}/system.json", "notes": "https://github.com/VoltaicGRiD/utopia-foundryvtt/releases/tag/${{ inputs.tag }}", "compatibility": { "minimum": "12", "verified": "12.133", "maximum": "12" } } }'
